#!/usr/bin/env tsx

import { chromium } from 'playwright'
import { writeFileSync } from 'fs'
import { join } from 'path'

async function generateSamplePDF() {
  console.log('🎨 [test-pdf] Starting sample PDF generation...')
  
  const browser = await chromium.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  })
  
  try {
    const page = await browser.newPage()
    
    // Set viewport for consistent rendering
    await page.setViewportSize({ width: 1200, height: 800 })
    
    // Navigate to sample PDF page
    const url = 'http://localhost:3000/report/sample/pdf'
    console.log(`🎨 [test-pdf] Navigating to: ${url}`)
    
    await page.goto(url, { 
      waitUntil: 'networkidle',
      timeout: 30000 
    })
    
    // Wait for content to load
    await page.waitForSelector('.header', { timeout: 10000 })
    console.log('🎨 [test-pdf] Page content loaded')
    
    // Generate PDF
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '15mm',
        bottom: '20mm',
        left: '15mm'
      },
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="font-size: 10px; color: #666; width: 100%; text-align: center; margin: 0 15mm;">
          <span>Accessibility Report - Generated by Auditvia</span>
        </div>
      `,
      footerTemplate: `
        <div style="font-size: 10px; color: #666; width: 100%; display: flex; justify-content: space-between; margin: 0 15mm;">
          <span>Confidential</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
          <span>${new Date().toLocaleDateString()}</span>
        </div>
      `,
      preferCSSPageSize: false,
    })
    
    // Save PDF to file
    const outputPath = join(process.cwd(), 'sample-accessibility-report.pdf')
    writeFileSync(outputPath, pdfBuffer)
    
    console.log(`🎨 [test-pdf] ✅ PDF generated successfully!`)
    console.log(`🎨 [test-pdf] File saved to: ${outputPath}`)
    console.log(`🎨 [test-pdf] File size: ${(pdfBuffer.length / 1024).toFixed(1)} KB`)
    
  } finally {
    await browser.close()
  }
}

// Run the test
generateSamplePDF().catch(console.error)
