'use client'

import { AlertTriangle } from 'lucide-react'
import { ScoreBadge } from '@/app/components/ui/ScoreBadge'
import { IssueList } from '@/app/components/ui/IssueList'

interface PublicScanReportProps {
  scan: any // TODO: Type this properly
}

export function PublicScanReport({ scan }: PublicScanReportProps) {
  const score = scan.score || 0
  const scoreText = score >= 90 ? 'Excellent' : score >= 70 ? 'Good' : 'Needs Improvement'

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Public Banner */}
      <div className="bg-blue-500 text-white py-2 px-4 text-center text-sm">
        This is a public accessibility report shared by Auditvia
      </div>

      <main className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-2xl font-semibold text-gray-900 dark:text-white mb-2">
            Accessibility Report for {scan.sites?.url}
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Scan completed {new Date(scan.finished_at).toLocaleDateString()}
          </p>
        </div>

        {/* Score Section */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-6 mb-8">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-xl font-medium text-gray-900 dark:text-white mb-2">
                Overall Score
              </h2>
              <p className="text-gray-600 dark:text-gray-400">
                {scoreText} accessibility compliance
              </p>
            </div>
            <ScoreBadge score={score} size="lg" />
          </div>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-6">
            <h3 className="text-sm font-medium text-gray-500 dark:text-gray-400 mb-1">
              Total Issues
            </h3>
            <p className="text-2xl font-semibold text-gray-900 dark:text-white">
              {scan.total_violations}
            </p>
          </div>
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-6">
            <h3 className="text-sm font-medium text-gray-500 dark:text-gray-400 mb-1">
              Passed Tests
            </h3>
            <p className="text-2xl font-semibold text-gray-900 dark:text-white">
              {scan.passes}
            </p>
          </div>
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-6">
            <h3 className="text-sm font-medium text-gray-500 dark:text-gray-400 mb-1">
              Scan Time
            </h3>
            <p className="text-2xl font-semibold text-gray-900 dark:text-white">
              {(scan.scan_time_ms / 1000).toFixed(1)}s
            </p>
          </div>
        </div>

        {/* Issues List */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-6">
          <h2 className="text-xl font-medium text-gray-900 dark:text-white mb-4">
            Accessibility Issues
          </h2>
          {scan.issues?.length > 0 ? (
            <IssueList issues={scan.issues} />
          ) : (
            <div className="text-center py-8">
              <AlertTriangle className="mx-auto h-12 w-12 text-gray-400" />
              <h3 className="mt-2 text-sm font-medium text-gray-900 dark:text-white">
                No issues found
              </h3>
              <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                This scan did not detect any accessibility issues.
              </p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="mt-8 text-center text-sm text-gray-500 dark:text-gray-400">
          <p>
            This report was generated by{' '}
            <a
              href="https://auditvia.com"
              className="text-blue-600 hover:text-blue-500 dark:text-blue-400 dark:hover:text-blue-300"
              target="_blank"
              rel="noopener noreferrer"
            >
              Auditvia
            </a>
          </p>
        </div>
      </main>
    </div>
  )
} 