name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  CI: true
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm@10.13.1

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run lint
        run: pnpm run lint --if-present

      - name: Run type-check
        run: pnpm run type-check --if-present

      - name: Build project
        run: pnpm run build --if-present

      - name: Run unit tests
        run: pnpm test --if-present -- --run
